CREATE TABLE Author_Name (
    id INT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    des TEXT,
    language_id INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (id) REFERENCES Author(id)
);
